import type {
  NextPage
} from "next";
import Head from "next/head";

import {
  Container
} from "reactstrap";

import TopNavigation from "components/TopNavigation";

const Home : NextPage = () => {
  return (
    <div>
      <Head>
        <title>HomePage</title>
        <meta
          name="description"
          content="Generated by create next app" />
        <link
          rel="icon"
          href="/favicon.ico" />
      </Head>
      <div>
        <TopNavigation />
        <div>
          <Container className="py-5">
            Home Page Content
          </Container>
        </div>
      </div>
    </div>
  );
};

export default Home;
