import type {
  NextPage
} from "next";
import Head from "next/head";

const JobsPage : NextPage = () => {
  return (
    <div>
      <Head>
        <title>HomePage</title>
        <meta
          name="description"
          content="Generated by create next app" />
        <link
          rel="icon"
          href="/favicon.ico" />
      </Head>
      <div>
        Job List Page
      </div>
    </div>
  );
};

export default JobsPage;
