import type { NextPage } from "next";
import Head from "next/head";
import { Container } from "reactstrap";
import styles from "../styles/Jobs.module.css";

const JobsPage: NextPage = () => {
	return (
		<div>
			<Head>
				<title>HomePage</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container className="py-5">
				<span className={styles.job_list_title}>Job List</span>
				<div className={styles.job_list_box}>
					<form className={styles.job_list_form}>
						<input
							className={styles.job_list_form_input}
							type="text"
							placeholder="Job Title"
						/>
						<input
							className={styles.job_list_form_input}
							type="text"
							placeholder="Location"
						/>
						<input
							className={styles.job_list_form_btn}
							type="submit"
							value="REFINE YOUR SEARCH"
						/>
					</form>
				</div>
			</Container>
		</div>
	);
};

export default JobsPage;
