export type Resume = {
    id: number,
        userId: number,
        resumeTitle: string,
        resumeType: string,
        resumeName: string,
        uploadedAt: string,
        fileType: string,
        resumeReferral?: null,
        referralId?: null,
        parentReferralId?: null,
        resumeStatus?: null,
        sharedWith?: null,
        targetAccessToken?: null,
        previewToken?: null,
        maskedLinkId: string,
        previewExpiresAt?: null,
        extendPreviewToken?: null,
        originalPreviewToken?: null,
        originalLinkId: string,
        originalPreviewExpiresAt?: null,
        extendOriginalPreviewToken?: null,
        listingActive: boolean,
        noOfReviews: number,
        noOfSkills: number,
        downloadFile?: null,
        ownerEmail: string
}
